const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');
const Papa = require('papaparse');
const CryptoJS = require('crypto-js');
const { normalizeProviderRecord } = require('./lib/provider-record');

// Load .secret_env if present (optional in CI)
const envPath = path.resolve(__dirname, '../.secret_env');
if (fs.existsSync(envPath)) {
  dotenv.config({ path: envPath });
}

// Single secret name; optional .secret_env already loaded for local dev
const SECRET_KEY = process.env.REACT_APP_SECRET_KEY;
if (!SECRET_KEY) {
  throw new Error('Missing secret: set REACT_APP_SECRET_KEY as a GitHub secret or provide it in .secret_env');
}

// Read and parse CSV. In CI, DATA_CSV_BASE64 is always set—use it and ignore local data.csv.
const csvPath = path.resolve(__dirname, '../data/data.csv');
let csvContent;
if (process.env.DATA_CSV_BASE64) {
  csvContent = Buffer.from(process.env.DATA_CSV_BASE64, 'base64').toString('utf8');
  console.log('Loaded CSV data from DATA_CSV_BASE64 environment variable.');
} else if (fs.existsSync(csvPath)) {
  csvContent = fs.readFileSync(csvPath, 'utf8');
} else {
  throw new Error('No data/data.csv file found and DATA_CSV_BASE64 environment variable is not set.');
}
const { data, errors } = Papa.parse(csvContent, {
  header: true,
  dynamicTyping: true,
  skipEmptyLines: true,
});
if (errors.length > 0) {
  console.error('CSV parsing errors:', errors);
}

const parsedData = (data).filter((item) => {
  return item.Latitude && item.Longitude &&
    !Number.isNaN(Number(item.Latitude)) && !Number.isNaN(Number(item.Longitude));
}).map((item) => normalizeProviderRecord(item));

// Encrypt JSON string
const jsonString = JSON.stringify(parsedData);
const encrypted = CryptoJS.AES.encrypt(jsonString, SECRET_KEY).toString();

// Write to src/secureDataBlob.ts
const outputPath = path.resolve(__dirname, '../src/secureDataBlob.ts');
const output = `// This file is auto-generated by scripts/process-data.js\nexport const ENCRYPTED_SPECIALISTS_DATA = "${encrypted}";\n`;
fs.writeFileSync(outputPath, output, 'utf8');
console.log('Encrypted data written to src/secureDataBlob.ts');

// Hash injection for App.tsx is handled by hash-secret.js and the CI workflow
