name: Update GitHub Secret

on:
  push:
    branches:
      - main
    paths:
      - '.secret_env'
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read secret from .secret_env
        id: read-secret
        run: |
          if [ -f .secret_env ]; then
            SECRET_VALUE=$(grep "REACT_APP_SECRET_KEY=" .secret_env | cut -d'=' -f2- | tr -d '"' | tr -d "'")
            echo "secret_value=$SECRET_VALUE" >> $GITHUB_OUTPUT
            echo "Secret found and extracted"
          else
            echo "Error: .secret_env file not found"
            exit 1
          fi

      - name: Update GitHub Repository Secret
        run: |
          echo "${{ steps.read-secret.outputs.secret_value }}" | gh secret set REACT_APP_SECRET_KEY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify secret update
        run: |
          echo "✅ GitHub secret REACT_APP_SECRET_KEY has been updated from .secret_env file"
