name: DEPRECATED - Do Not Use (Secrets updater disabled)

on:
  # Intentionally disabled; left in repo for historical reference only
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated and does nothing. Use Deploy to GitHub Pages workflow."
